version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./public/static:/code/public/static
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./public/static:/code/public/static
    ports:
      - "80:80"
    links:
      - web

volumes:
  postgres_data:
